name: CIPHER
favicon: null
layout_spectrum: 0.020850158063694835
typography_spectrum: 0.8327087126672268
title: Cipher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060604'
    - '#c9c9c9'
    - '#a2a2a2'
    - '#777777'
    - '#404040'
  brandStrength: 0.75
  lightness: 0.9744864064268768
  saturation: 0.905482872389257
  rhythmicContrast: 0.9246743926778436
purpose: []
