name: CIPHER
favicon: null
layout_spectrum: 0.63743
typography_spectrum: 0.86264
title: Cipher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060604'
    - '#c9c9c9'
    - '#a2a2a2'
    - '#777777'
    - '#404040'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
