name: cipher
favicon: null
layout_spectrum: 0.020850158063694835
typography_spectrum: 0.8327087126672268
title: Cipher
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6342629429418594
  lightness: 0.9744864064268768
  saturation: 0.905482872389257
  rhythmicContrast: 0.9246743926778436
purpose: []
